# Generated by Django 6.0.1 on 2026-04-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_claim_proof_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='base64_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
